version: "3.8"

services:
  nginx:
    build: .
    image: ${{ secrets.DOCKER_USERNAME }}/nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    build: .
    image: ${{ secrets.DOCKER_USERNAME }}/mariadb:latest
    container_name: mariadb_server
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"

  wazuh:
    build: .
    image: ${{ secrets.DOCKER_USERNAME }}/wazuh:4.4.0
    container_name: wazuh_server
    ports:
      - "1514:1514"
      - "1515:1515"
      - "55000:55000"
    environment:
      - ELASTIC_VERSION=7.10.2

