name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar Docker y Docker Compose
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Paso 3: Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Paso 4: Construir y subir imágenes Docker
      - name: Build and push Docker images
        run: |
          # Construir la imagen de nginx
          docker build -t "${{ secrets.DOCKER_USERNAME }}/nginx:latest" -f ./Dockerfile .
          docker push "${{ secrets.DOCKER_USERNAME }}/nginx:latest"

          # Construir la imagen de mariadb
          docker build -t "${{ secrets.DOCKER_USERNAME }}/mariadb:latest" -f ./Dockerfile .
          docker push "${{ secrets.DOCKER_USERNAME }}/mariadb:latest"

          # Construir la imagen de wazuh
          docker build -t "${{ secrets.DOCKER_USERNAME }}/wazuh:latest" -f ./Dockerfile .
          docker push "${{ secrets.DOCKER_USERNAME }}/wazuh:latest"

      # Paso 5: Desplegar los servicios con Docker Compose
      - name: Deploy with Docker Compose
        run: |
          docker-compose up -d

