name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Paso 3: Construir y subir imágenes Docker
      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      # Paso 4: Desplegar los servicios
      - name: Deploy with Docker Compose
        run: docker-compose up -d

