name: Deploy Project

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml up -d --build

    - name: Restart services with Docker Compose
      run: |
        docker-compose -f docker-compose.yml down
        docker-compose -f docker-compose.yml up -d

    - name: Notify Deployment Status
      uses: peter-evans/slack-notify@v2
      with:
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
        message: "Deployment successful!"


